//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDG.WEB.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Embed {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Embed() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BDG.WEB.Resources.Embed", typeof(Embed).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string TextAlbum {
            get {
                return ResourceManager.GetString("TextAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string TextArtist {
            get {
                return ResourceManager.GetString("TextArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Play.
        /// </summary>
        public static string TextAutoPlay {
            get {
                return ResourceManager.GetString("TextAutoPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed.
        /// </summary>
        public static string TextEmbed {
            get {
                return ResourceManager.GetString("TextEmbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure and copy your embed code..
        /// </summary>
        public static string TextExplain {
            get {
                return ResourceManager.GetString("TextExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed Code.
        /// </summary>
        public static string TextGeneratedCode {
            get {
                return ResourceManager.GetString("TextGeneratedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string TextHeight {
            get {
                return ResourceManager.GetString("TextHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string TextMusic {
            get {
                return ResourceManager.GetString("TextMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        public static string TextPlaylist {
            get {
                return ResourceManager.GetString("TextPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string TextPreview {
            get {
                return ResourceManager.GetString("TextPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string TextTheme {
            get {
                return ResourceManager.GetString("TextTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BDG.
        /// </summary>
        public static string TextThemeBDG {
            get {
                return ResourceManager.GetString("TextThemeBDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string TextThemeDark {
            get {
                return ResourceManager.GetString("TextThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string TextThemeLight {
            get {
                return ResourceManager.GetString("TextThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to song.
        /// </summary>
        public static string TextTotalSong {
            get {
                return ResourceManager.GetString("TextTotalSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to song(s).
        /// </summary>
        public static string TextTotalSongs {
            get {
                return ResourceManager.GetString("TextTotalSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string TextView {
            get {
                return ResourceManager.GetString("TextView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverart.
        /// </summary>
        public static string TextViewCoverart {
            get {
                return ResourceManager.GetString("TextViewCoverart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string TextViewList {
            get {
                return ResourceManager.GetString("TextViewList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string TextViewPlayer {
            get {
                return ResourceManager.GetString("TextViewPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string TextWidth {
            get {
                return ResourceManager.GetString("TextWidth", resourceCulture);
            }
        }
    }
}
