//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDG.WEB.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Login {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Login() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BDG.WEB.Resources.Login", typeof(Login).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field BirthDate is invalid..
        /// </summary>
        public static string DataField_BirthDate_DataType_Date {
            get {
                return ResourceManager.GetString("DataField_BirthDate_DataType_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BirthDate (dd/mm/yyyy).
        /// </summary>
        public static string DataField_BirthDate_Label {
            get {
                return ResourceManager.GetString("DataField_BirthDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field BirthDate is required..
        /// </summary>
        public static string DataField_BirthDate_Required {
            get {
                return ResourceManager.GetString("DataField_BirthDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string DataField_City_Label {
            get {
                return ResourceManager.GetString("DataField_City_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select City.
        /// </summary>
        public static string DataField_City_OptionDefault {
            get {
                return ResourceManager.GetString("DataField_City_OptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field City is required..
        /// </summary>
        public static string DataField_City_Required {
            get {
                return ResourceManager.GetString("DataField_City_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string DataField_Country_Label {
            get {
                return ResourceManager.GetString("DataField_Country_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country does not exist..
        /// </summary>
        public static string DataField_Country_NotExist {
            get {
                return ResourceManager.GetString("DataField_Country_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country.
        /// </summary>
        public static string DataField_Country_OptionDefault {
            get {
                return ResourceManager.GetString("DataField_Country_OptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Country is required..
        /// </summary>
        public static string DataField_Country_Required {
            get {
                return ResourceManager.GetString("DataField_Country_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Email is invalid..
        /// </summary>
        public static string DataField_Email_DataType_EmailAddress {
            get {
                return ResourceManager.GetString("DataField_Email_DataType_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This e-mail is already in use..
        /// </summary>
        public static string DataField_Email_Exist {
            get {
                return ResourceManager.GetString("DataField_Email_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string DataField_Email_Label {
            get {
                return ResourceManager.GetString("DataField_Email_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email does not exist..
        /// </summary>
        public static string DataField_Email_NotExist {
            get {
                return ResourceManager.GetString("DataField_Email_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Email is required..
        /// </summary>
        public static string DataField_Email_Required {
            get {
                return ResourceManager.GetString("DataField_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is invalid..
        /// </summary>
        public static string DataField_EmailNotSend {
            get {
                return ResourceManager.GetString("DataField_EmailNotSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string DataField_Gender_Label {
            get {
                return ResourceManager.GetString("DataField_Gender_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Gender.
        /// </summary>
        public static string DataField_Gender_OptionDefault {
            get {
                return ResourceManager.GetString("DataField_Gender_OptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Gender is required..
        /// </summary>
        public static string DataField_Gender_Required {
            get {
                return ResourceManager.GetString("DataField_Gender_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or Password invalid, check and try again..
        /// </summary>
        public static string DataField_InvalidLogin {
            get {
                return ResourceManager.GetString("DataField_InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DataField_Name_Label {
            get {
                return ResourceManager.GetString("DataField_Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Name is required..
        /// </summary>
        public static string DataField_Name_Required {
            get {
                return ResourceManager.GetString("DataField_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string DataField_Password_Label {
            get {
                return ResourceManager.GetString("DataField_Password_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Password is required..
        /// </summary>
        public static string DataField_Password_Required {
            get {
                return ResourceManager.GetString("DataField_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Password must be at least 6 characters and a maximum 10..
        /// </summary>
        public static string DataField_Password_StringLength {
            get {
                return ResourceManager.GetString("DataField_Password_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Confirmation.
        /// </summary>
        public static string DataField_PasswordConfirmation_Label {
            get {
                return ResourceManager.GetString("DataField_PasswordConfirmation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Password Confirmation is required..
        /// </summary>
        public static string DataField_PasswordConfirmation_Required {
            get {
                return ResourceManager.GetString("DataField_PasswordConfirmation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string DataField_State_Label {
            get {
                return ResourceManager.GetString("DataField_State_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State does not exist..
        /// </summary>
        public static string DataField_State_NotExist {
            get {
                return ResourceManager.GetString("DataField_State_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select State.
        /// </summary>
        public static string DataField_State_OptionDefault {
            get {
                return ResourceManager.GetString("DataField_State_OptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field State is required..
        /// </summary>
        public static string DataField_State_Required {
            get {
                return ResourceManager.GetString("DataField_State_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree the terms and policy.
        /// </summary>
        public static string DataField_Terms_Label {
            get {
                return ResourceManager.GetString("DataField_Terms_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Terms is required..
        /// </summary>
        public static string DataField_Terms_Required {
            get {
                return ResourceManager.GetString("DataField_Terms_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string LabelSignUp {
            get {
                return ResourceManager.GetString("LabelSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up with Facebook.
        /// </summary>
        public static string LabelSignUpFacebook {
            get {
                return ResourceManager.GetString("LabelSignUpFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successfully..
        /// </summary>
        public static string ReturnSignUpSuccess {
            get {
                return ResourceManager.GetString("ReturnSignUpSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string TextAlreadyHaveAccount {
            get {
                return ResourceManager.GetString("TextAlreadyHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate your Facebook account.
        /// </summary>
        public static string TextAssociateFacebook {
            get {
                return ResourceManager.GetString("TextAssociateFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string TextCloseButton {
            get {
                return ResourceManager.GetString("TextCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string TextConfirmButton {
            get {
                return ResourceManager.GetString("TextConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        public static string TextCreateAccount {
            get {
                return ResourceManager.GetString("TextCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string TextDontHaveAccount {
            get {
                return ResourceManager.GetString("TextDontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string TextForgotPasswordButton {
            get {
                return ResourceManager.GetString("TextForgotPasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string TextLoginButton {
            get {
                return ResourceManager.GetString("TextLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful login with service..
        /// </summary>
        public static string TextLoginUnsuccessfulService {
            get {
                return ResourceManager.GetString("TextLoginUnsuccessfulService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password updated..
        /// </summary>
        public static string TextNewPasswordChangedSuccess {
            get {
                return ResourceManager.GetString("TextNewPasswordChangedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password was sent to &apos;{0}&apos;..
        /// </summary>
        public static string TextNewPasswordSuccess {
            get {
                return ResourceManager.GetString("TextNewPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up to make part of a new music.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
