//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDG.WEB.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProfileEditArtist {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfileEditArtist() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BDG.WEB.Resources.ProfileEditArtist", typeof(ProfileEditArtist).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must change this picture. This picture have ##WIDTH##x##HEIGHT##..
        /// </summary>
        public static string TextAlertChangePicture {
            get {
                return ResourceManager.GetString("TextAlertChangePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm delete this artist?.
        /// </summary>
        public static string TextConfirmDelete {
            get {
                return ResourceManager.GetString("TextConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Artist.
        /// </summary>
        public static string TextDeleteButton {
            get {
                return ResourceManager.GetString("TextDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Artist / Band.
        /// </summary>
        public static string TextNewButton {
            get {
                return ResourceManager.GetString("TextNewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TextOrderName {
            get {
                return ResourceManager.GetString("TextOrderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Albuns.
        /// </summary>
        public static string TextOrderTotalAlbum {
            get {
                return ResourceManager.GetString("TextOrderTotalAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Listens.
        /// </summary>
        public static string TextOrderTotalListens {
            get {
                return ResourceManager.GetString("TextOrderTotalListens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Songs.
        /// </summary>
        public static string TextOrderTotalMusic {
            get {
                return ResourceManager.GetString("TextOrderTotalMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Views.
        /// </summary>
        public static string TextOrderTotalViews {
            get {
                return ResourceManager.GetString("TextOrderTotalViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add as Administrator.
        /// </summary>
        public static string TextProfileAccessAddAsAdministrator {
            get {
                return ResourceManager.GetString("TextProfileAccessAddAsAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add as User.
        /// </summary>
        public static string TextProfileAccessAddAsUser {
            get {
                return ResourceManager.GetString("TextProfileAccessAddAsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string TextProfileAccessAdministrator {
            get {
                return ResourceManager.GetString("TextProfileAccessAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        public static string TextProfileAccessDatePermission {
            get {
                return ResourceManager.GetString("TextProfileAccessDatePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TextProfileAccessDelete {
            get {
                return ResourceManager.GetString("TextProfileAccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string TextProfileAccessEmail {
            get {
                return ResourceManager.GetString("TextProfileAccessEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TextProfileAccessName {
            get {
                return ResourceManager.GetString("TextProfileAccessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find profile to grant access.
        /// </summary>
        public static string TextProfileAccessSearch {
            get {
                return ResourceManager.GetString("TextProfileAccessSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Artists.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist Edit.
        /// </summary>
        public static string TitleEdit {
            get {
                return ResourceManager.GetString("TitleEdit", resourceCulture);
            }
        }
    }
}
