//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBDG.Resx.Models {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EditEventValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditEventValidation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobileBDG.Resx.Models.EditEventValidation", typeof(EditEventValidation).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        internal static string DataField_Artist_Label {
            get {
                return ResourceManager.GetString("DataField_Artist_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Artist.
        /// </summary>
        internal static string DataField_Artist_OptionDefault {
            get {
                return ResourceManager.GetString("DataField_Artist_OptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Artist is required..
        /// </summary>
        internal static string DataField_Artist_Required {
            get {
                return ResourceManager.GetString("DataField_Artist_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string DataField_City_Label {
            get {
                return ResourceManager.GetString("DataField_City_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field City is required..
        /// </summary>
        internal static string DataField_City_Required {
            get {
                return ResourceManager.GetString("DataField_City_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string DataField_Country_Label {
            get {
                return ResourceManager.GetString("DataField_Country_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country.
        /// </summary>
        internal static string DataField_Country_OptionDefault {
            get {
                return ResourceManager.GetString("DataField_Country_OptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Country is required..
        /// </summary>
        internal static string DataField_Country_Required {
            get {
                return ResourceManager.GetString("DataField_Country_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Date is invalid..
        /// </summary>
        internal static string DataField_Date_DataType_Date {
            get {
                return ResourceManager.GetString("DataField_Date_DataType_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string DataField_Date_Label {
            get {
                return ResourceManager.GetString("DataField_Date_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Date is required..
        /// </summary>
        internal static string DataField_Date_Required {
            get {
                return ResourceManager.GetString("DataField_Date_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DataField_Description_Label {
            get {
                return ResourceManager.GetString("DataField_Description_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Description is required..
        /// </summary>
        internal static string DataField_Description_Required {
            get {
                return ResourceManager.GetString("DataField_Description_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        internal static string DataField_Image_Label {
            get {
                return ResourceManager.GetString("DataField_Image_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Picture is required..
        /// </summary>
        internal static string DataField_Image_Required {
            get {
                return ResourceManager.GetString("DataField_Image_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string DataField_Local_Label {
            get {
                return ResourceManager.GetString("DataField_Local_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Local is required..
        /// </summary>
        internal static string DataField_Local_Required {
            get {
                return ResourceManager.GetString("DataField_Local_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Local must be at least 3 characters and a maximum 250..
        /// </summary>
        internal static string DataField_Local_StringLength {
            get {
                return ResourceManager.GetString("DataField_Local_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL is not valid..
        /// </summary>
        internal static string DataField_Site_Invalid {
            get {
                return ResourceManager.GetString("DataField_Site_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string DataField_Title_Label {
            get {
                return ResourceManager.GetString("DataField_Title_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Title is required..
        /// </summary>
        internal static string DataField_Title_Required {
            get {
                return ResourceManager.GetString("DataField_Title_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Title must be at least 3 characters and a maximum 250..
        /// </summary>
        internal static string DataField_Title_StringLength {
            get {
                return ResourceManager.GetString("DataField_Title_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event deleted successfully..
        /// </summary>
        internal static string ReturnSuccessDelete {
            get {
                return ResourceManager.GetString("ReturnSuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New event added successfully..
        /// </summary>
        internal static string ReturnSuccessNew {
            get {
                return ResourceManager.GetString("ReturnSuccessNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event updated successfully..
        /// </summary>
        internal static string ReturnSuccessUpdate {
            get {
                return ResourceManager.GetString("ReturnSuccessUpdate", resourceCulture);
            }
        }
    }
}
