//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDG.WEB.Resources.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditAlbumValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditAlbumValidation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BDG.WEB.Resources.Models.EditAlbumValidation", typeof(EditAlbumValidation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string DataField_Artist_Label {
            get {
                return ResourceManager.GetString("DataField_Artist_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Artist.
        /// </summary>
        public static string DataField_Artist_OptionDefault {
            get {
                return ResourceManager.GetString("DataField_Artist_OptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Artist is required..
        /// </summary>
        public static string DataField_Artist_Required {
            get {
                return ResourceManager.GetString("DataField_Artist_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Buy Link URL is not valid..
        /// </summary>
        public static string DataField_BuyLink_Invalid {
            get {
                return ResourceManager.GetString("DataField_BuyLink_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Link.
        /// </summary>
        public static string DataField_BuyLink_Label {
            get {
                return ResourceManager.GetString("DataField_BuyLink_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical Genre.
        /// </summary>
        public static string DataField_Genre_Label {
            get {
                return ResourceManager.GetString("DataField_Genre_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Genre.
        /// </summary>
        public static string DataField_Genre_OptionDefault {
            get {
                return ResourceManager.GetString("DataField_Genre_OptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Musical Genre is required..
        /// </summary>
        public static string DataField_Genre_Required {
            get {
                return ResourceManager.GetString("DataField_Genre_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string DataField_Image_Label {
            get {
                return ResourceManager.GetString("DataField_Image_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Picture is required..
        /// </summary>
        public static string DataField_Image_Required {
            get {
                return ResourceManager.GetString("DataField_Image_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DataField_Name_Label {
            get {
                return ResourceManager.GetString("DataField_Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Name is required..
        /// </summary>
        public static string DataField_Name_Required {
            get {
                return ResourceManager.GetString("DataField_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Name must be maximum 250 characters..
        /// </summary>
        public static string DataField_Name_StringLength {
            get {
                return ResourceManager.GetString("DataField_Name_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string DataField_Year_Label {
            get {
                return ResourceManager.GetString("DataField_Year_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Year is required..
        /// </summary>
        public static string DataField_Year_Required {
            get {
                return ResourceManager.GetString("DataField_Year_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album deleted successfully..
        /// </summary>
        public static string ReturnSuccessDelete {
            get {
                return ResourceManager.GetString("ReturnSuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New album added successfully..
        /// </summary>
        public static string ReturnSuccessNew {
            get {
                return ResourceManager.GetString("ReturnSuccessNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album updated successfully..
        /// </summary>
        public static string ReturnSuccessUpdate {
            get {
                return ResourceManager.GetString("ReturnSuccessUpdate", resourceCulture);
            }
        }
    }
}
