//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDG.WEB.Resources.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditArtistValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditArtistValidation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BDG.WEB.Resources.Models.EditArtistValidation", typeof(EditArtistValidation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        public static string DataField_About_Label {
            get {
                return ResourceManager.GetString("DataField_About_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artista.
        /// </summary>
        public static string DataField_Artist_Label {
            get {
                return ResourceManager.GetString("DataField_Artist_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el Artista.
        /// </summary>
        public static string DataField_Artist_OptionDefault {
            get {
                return ResourceManager.GetString("DataField_Artist_OptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el Artista.
        /// </summary>
        public static string DataField_Artist_Required {
            get {
                return ResourceManager.GetString("DataField_Artist_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string DataField_City_Label {
            get {
                return ResourceManager.GetString("DataField_City_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select City.
        /// </summary>
        public static string DataField_City_OptionDefault {
            get {
                return ResourceManager.GetString("DataField_City_OptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field City is required..
        /// </summary>
        public static string DataField_City_Required {
            get {
                return ResourceManager.GetString("DataField_City_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string DataField_Country_Label {
            get {
                return ResourceManager.GetString("DataField_Country_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country does not exist..
        /// </summary>
        public static string DataField_Country_NotExist {
            get {
                return ResourceManager.GetString("DataField_Country_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country.
        /// </summary>
        public static string DataField_Country_OptionDefault {
            get {
                return ResourceManager.GetString("DataField_Country_OptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Country is required..
        /// </summary>
        public static string DataField_Country_Required {
            get {
                return ResourceManager.GetString("DataField_Country_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical Genre.
        /// </summary>
        public static string DataField_Genre_Label {
            get {
                return ResourceManager.GetString("DataField_Genre_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Genre.
        /// </summary>
        public static string DataField_Genre_OptionDefault {
            get {
                return ResourceManager.GetString("DataField_Genre_OptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Musical Genre is required..
        /// </summary>
        public static string DataField_Genre_Required {
            get {
                return ResourceManager.GetString("DataField_Genre_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string DataField_Image_Label {
            get {
                return ResourceManager.GetString("DataField_Image_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Picture is required..
        /// </summary>
        public static string DataField_Image_Required {
            get {
                return ResourceManager.GetString("DataField_Image_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DataField_Name_Label {
            get {
                return ResourceManager.GetString("DataField_Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Name is required..
        /// </summary>
        public static string DataField_Name_Required {
            get {
                return ResourceManager.GetString("DataField_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Name must be at least 3 characters and a maximum 250..
        /// </summary>
        public static string DataField_Name_StringLength {
            get {
                return ResourceManager.GetString("DataField_Name_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Oficial Site URL is not valid..
        /// </summary>
        public static string DataField_Site_Invalid {
            get {
                return ResourceManager.GetString("DataField_Site_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oficial Site.
        /// </summary>
        public static string DataField_Site_Label {
            get {
                return ResourceManager.GetString("DataField_Site_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string DataField_State_Label {
            get {
                return ResourceManager.GetString("DataField_State_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State does not exist..
        /// </summary>
        public static string DataField_State_NotExist {
            get {
                return ResourceManager.GetString("DataField_State_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select State.
        /// </summary>
        public static string DataField_State_OptionDefault {
            get {
                return ResourceManager.GetString("DataField_State_OptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field State is required..
        /// </summary>
        public static string DataField_State_Required {
            get {
                return ResourceManager.GetString("DataField_State_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist deleted successfully..
        /// </summary>
        public static string ReturnSuccessDelete {
            get {
                return ResourceManager.GetString("ReturnSuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New artist added successfully..
        /// </summary>
        public static string ReturnSuccessNew {
            get {
                return ResourceManager.GetString("ReturnSuccessNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist updated successfully..
        /// </summary>
        public static string ReturnSuccessUpdate {
            get {
                return ResourceManager.GetString("ReturnSuccessUpdate", resourceCulture);
            }
        }
    }
}
