//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBDG.Resx.Models {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EditMusicValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditMusicValidation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobileBDG.Resx.Models.EditMusicValidation", typeof(EditMusicValidation).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        internal static string DataField_Album_Label {
            get {
                return ResourceManager.GetString("DataField_Album_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Album.
        /// </summary>
        internal static string DataField_Album_OptionDefault {
            get {
                return ResourceManager.GetString("DataField_Album_OptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Album is required..
        /// </summary>
        internal static string DataField_Album_Required {
            get {
                return ResourceManager.GetString("DataField_Album_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        internal static string DataField_Artist_Label {
            get {
                return ResourceManager.GetString("DataField_Artist_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Artist.
        /// </summary>
        internal static string DataField_Artist_OptionDefault {
            get {
                return ResourceManager.GetString("DataField_Artist_OptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Artist is required..
        /// </summary>
        internal static string DataField_Artist_Required {
            get {
                return ResourceManager.GetString("DataField_Artist_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string DataField_Author_Label {
            get {
                return ResourceManager.GetString("DataField_Author_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Author is required..
        /// </summary>
        internal static string DataField_Author_Required {
            get {
                return ResourceManager.GetString("DataField_Author_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Author must be at least 3 characters and a maximum 250..
        /// </summary>
        internal static string DataField_Author_StringLength {
            get {
                return ResourceManager.GetString("DataField_Author_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string DataField_Name_Label {
            get {
                return ResourceManager.GetString("DataField_Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Name is required..
        /// </summary>
        internal static string DataField_Name_Required {
            get {
                return ResourceManager.GetString("DataField_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Name must be at least 3 characters and a maximum 250..
        /// </summary>
        internal static string DataField_Name_StringLength {
            get {
                return ResourceManager.GetString("DataField_Name_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 128kbps (recommended).
        /// </summary>
        internal static string InfoFileMaxBitrate {
            get {
                return ResourceManager.GetString("InfoFileMaxBitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max 10 files per upload..
        /// </summary>
        internal static string InfoFileMaxUpload {
            get {
                return ResourceManager.GetString("InfoFileMaxUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max 20 MB per file..
        /// </summary>
        internal static string InfoFileSize {
            get {
                return ResourceManager.GetString("InfoFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload just mp3 files..
        /// </summary>
        internal static string InfoFileType {
            get {
                return ResourceManager.GetString("InfoFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song deleted successfully..
        /// </summary>
        internal static string ReturnSuccessDelete {
            get {
                return ResourceManager.GetString("ReturnSuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New song added successfully..
        /// </summary>
        internal static string ReturnSuccessNew {
            get {
                return ResourceManager.GetString("ReturnSuccessNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song updated successfully..
        /// </summary>
        internal static string ReturnSuccessUpdate {
            get {
                return ResourceManager.GetString("ReturnSuccessUpdate", resourceCulture);
            }
        }
    }
}
