//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDG.WEB.Resources.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditPlaylistValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditPlaylistValidation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BDG.WEB.Resources.Models.EditPlaylistValidation", typeof(EditPlaylistValidation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playlist name.
        /// </summary>
        public static string DataField_Title_Label {
            get {
                return ResourceManager.GetString("DataField_Title_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Name is required..
        /// </summary>
        public static string DataField_Title_Required {
            get {
                return ResourceManager.GetString("DataField_Title_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Name must be at least 2 characters and a maximum 40..
        /// </summary>
        public static string DataField_Title_StringLength {
            get {
                return ResourceManager.GetString("DataField_Title_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist deleted successfully..
        /// </summary>
        public static string ReturnSuccessDelete {
            get {
                return ResourceManager.GetString("ReturnSuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New playlist added successfully..
        /// </summary>
        public static string ReturnSuccessNew {
            get {
                return ResourceManager.GetString("ReturnSuccessNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist updated successfully..
        /// </summary>
        public static string ReturnSuccessUpdate {
            get {
                return ResourceManager.GetString("ReturnSuccessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Playlist.
        /// </summary>
        public static string TextNewButton {
            get {
                return ResourceManager.GetString("TextNewButton", resourceCulture);
            }
        }
    }
}
