//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBDG.Resx.Models {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SignUpFormValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SignUpFormValidation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobileBDG.Resx.Models.SignUpFormValidation", typeof(SignUpFormValidation).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Birthdate is invalid..
        /// </summary>
        internal static string DataField_BirthDate_DataType_Date {
            get {
                return ResourceManager.GetString("DataField_BirthDate_DataType_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        internal static string DataField_BirthDate_Label {
            get {
                return ResourceManager.GetString("DataField_BirthDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Birthdate is required..
        /// </summary>
        internal static string DataField_BirthDate_Required {
            get {
                return ResourceManager.GetString("DataField_BirthDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string DataField_City_Label {
            get {
                return ResourceManager.GetString("DataField_City_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select City.
        /// </summary>
        internal static string DataField_City_OptionDefault {
            get {
                return ResourceManager.GetString("DataField_City_OptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field City is required..
        /// </summary>
        internal static string DataField_City_Required {
            get {
                return ResourceManager.GetString("DataField_City_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string DataField_Country_Label {
            get {
                return ResourceManager.GetString("DataField_Country_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country.
        /// </summary>
        internal static string DataField_Country_OptionDefault {
            get {
                return ResourceManager.GetString("DataField_Country_OptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Country is required..
        /// </summary>
        internal static string DataField_Country_Required {
            get {
                return ResourceManager.GetString("DataField_Country_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Email is invalid..
        /// </summary>
        internal static string DataField_Email_DataType_EmailAddress {
            get {
                return ResourceManager.GetString("DataField_Email_DataType_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string DataField_Email_Label {
            get {
                return ResourceManager.GetString("DataField_Email_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Email must be at maximum 255 characters..
        /// </summary>
        internal static string DataField_Email_MaxLength {
            get {
                return ResourceManager.GetString("DataField_Email_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Email is required..
        /// </summary>
        internal static string DataField_Email_Required {
            get {
                return ResourceManager.GetString("DataField_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string DataField_Gender_Label {
            get {
                return ResourceManager.GetString("DataField_Gender_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Gender is required..
        /// </summary>
        internal static string DataField_Gender_Required {
            get {
                return ResourceManager.GetString("DataField_Gender_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string DataField_Name_Label {
            get {
                return ResourceManager.GetString("DataField_Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Name is required..
        /// </summary>
        internal static string DataField_Name_Required {
            get {
                return ResourceManager.GetString("DataField_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Name must be at least 5 characters and a maximum 150..
        /// </summary>
        internal static string DataField_Name_StringLength {
            get {
                return ResourceManager.GetString("DataField_Name_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string DataField_State_Label {
            get {
                return ResourceManager.GetString("DataField_State_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select State.
        /// </summary>
        internal static string DataField_State_OptionDefault {
            get {
                return ResourceManager.GetString("DataField_State_OptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field State is required..
        /// </summary>
        internal static string DataField_State_Required {
            get {
                return ResourceManager.GetString("DataField_State_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field BDG ID must be alphanumeric without special characters..
        /// </summary>
        internal static string DataField_UniqueName_DateType_Alpha {
            get {
                return ResourceManager.GetString("DataField_UniqueName_DateType_Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BDG ID {0} is already in use..
        /// </summary>
        internal static string DataField_UniqueName_InUse {
            get {
                return ResourceManager.GetString("DataField_UniqueName_InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BDG ID.
        /// </summary>
        internal static string DataField_UniqueName_Label {
            get {
                return ResourceManager.GetString("DataField_UniqueName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field BDG ID is required..
        /// </summary>
        internal static string DataField_UniqueName_Required {
            get {
                return ResourceManager.GetString("DataField_UniqueName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field BDG ID must be at least 5 characters and a maximum 150..
        /// </summary>
        internal static string DataField_UniqueName_StringLength {
            get {
                return ResourceManager.GetString("DataField_UniqueName_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated successfuly..
        /// </summary>
        internal static string ReturnSuccess {
            get {
                return ResourceManager.GetString("ReturnSuccess", resourceCulture);
            }
        }
    }
}
