//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDG.WEB.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BDG.WEB.Resources.Shared.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Email Templates..
        /// </summary>
        public static string ConfigureEmailTemplates {
            get {
                return ResourceManager.GetString("ConfigureEmailTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your photo.
        /// </summary>
        public static string filetext {
            get {
                return ResourceManager.GetString("filetext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to showing {0}-{1} of {2} items.
        /// </summary>
        public static string PaggingFooterText {
            get {
                return ResourceManager.GetString("PaggingFooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Profile.
        /// </summary>
        public static string TextAccessProfile {
            get {
                return ResourceManager.GetString("TextAccessProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to playlist.
        /// </summary>
        public static string TextAddToPlaylist {
            get {
                return ResourceManager.GetString("TextAddToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BDG Related Artists.
        /// </summary>
        public static string TextArticleArtistRelated {
            get {
                return ResourceManager.GetString("TextArticleArtistRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string TextArticleBy {
            get {
                return ResourceManager.GetString("TextArticleBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        public static string TextArtistRelease {
            get {
                return ResourceManager.GetString("TextArtistRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string TextArtistShare {
            get {
                return ResourceManager.GetString("TextArtistShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string TextArtistVideo {
            get {
                return ResourceManager.GetString("TextArtistVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string TextBackButton {
            get {
                return ResourceManager.GetString("TextBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BDG Recommend.
        /// </summary>
        public static string TextBDGRecommend {
            get {
                return ResourceManager.GetString("TextBDGRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BDG Discover New Music.
        /// </summary>
        public static string TextCaptionFacebook {
            get {
                return ResourceManager.GetString("TextCaptionFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string TextCloseButton {
            get {
                return ResourceManager.GetString("TextCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columnists.
        /// </summary>
        public static string TextColumnists {
            get {
                return ResourceManager.GetString("TextColumnists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue to the BDG.
        /// </summary>
        public static string TextContinue {
            get {
                return ResourceManager.GetString("TextContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string TextDownload {
            get {
                return ResourceManager.GetString("TextDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TextDropZoneCancelButton {
            get {
                return ResourceManager.GetString("TextDropZoneCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TextDropZoneDeleteButton {
            get {
                return ResourceManager.GetString("TextDropZoneDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string TextDropZoneEditButton {
            get {
                return ResourceManager.GetString("TextDropZoneEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string TextDropZoneSaveButton {
            get {
                return ResourceManager.GetString("TextDropZoneSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        public static string TextDropZoneZoomInButton {
            get {
                return ResourceManager.GetString("TextDropZoneZoomInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        public static string TextDropZoneZoomOutButton {
            get {
                return ResourceManager.GetString("TextDropZoneZoomOutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Size.
        /// </summary>
        public static string TextDropZoneZoomResetButton {
            get {
                return ResourceManager.GetString("TextDropZoneZoomResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string TextEdit {
            get {
                return ResourceManager.GetString("TextEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed.
        /// </summary>
        public static string TextEmbed {
            get {
                return ResourceManager.GetString("TextEmbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string TextFavorite {
            get {
                return ResourceManager.GetString("TextFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go!.
        /// </summary>
        public static string TextGoButton {
            get {
                return ResourceManager.GetString("TextGoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout error..
        /// </summary>
        public static string TextLogoutFail {
            get {
                return ResourceManager.GetString("TextLogoutFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to most read.
        /// </summary>
        public static string TextMostReady {
            get {
                return ResourceManager.GetString("TextMostReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string TextNoButton {
            get {
                return ResourceManager.GetString("TextNoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no records to display..
        /// </summary>
        public static string TextNoRecord {
            get {
                return ResourceManager.GetString("TextNoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no events to display..
        /// </summary>
        public static string TextNoRecordEvent {
            get {
                return ResourceManager.GetString("TextNoRecordEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait, processing....
        /// </summary>
        public static string TextProccessModal {
            get {
                return ResourceManager.GetString("TextProccessModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string TextSaveButton {
            get {
                return ResourceManager.GetString("TextSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search artists, albums, songs and people....
        /// </summary>
        public static string TextSearchField {
            get {
                return ResourceManager.GetString("TextSearchField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string TextSearchLabel {
            get {
                return ResourceManager.GetString("TextSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete at least 3 characters..
        /// </summary>
        public static string TextSearchMinChars {
            get {
                return ResourceManager.GetString("TextSearchMinChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to see all.
        /// </summary>
        public static string TextSeeAll {
            get {
                return ResourceManager.GetString("TextSeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to BDG, soon we will have a ranking with all artists.
        ///
        /// Enjoy your trip through our new house..
        /// </summary>
        public static string TextTempRanking {
            get {
                return ResourceManager.GetString("TextTempRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfavorite.
        /// </summary>
        public static string TextUnfavorite {
            get {
                return ResourceManager.GetString("TextUnfavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select files....
        /// </summary>
        public static string TextUploadSelectFiles {
            get {
                return ResourceManager.GetString("TextUploadSelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to confirm the image formatting..
        /// </summary>
        public static string TextValidationImageConfirm {
            get {
                return ResourceManager.GetString("TextValidationImageConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist verified by BDG.
        /// </summary>
        public static string TextVerifiedArtist {
            get {
                return ResourceManager.GetString("TextVerifiedArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string TextYesButton {
            get {
                return ResourceManager.GetString("TextYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BDG | Discover New Music.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
    }
}
